services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python seed_data.py && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
