# Generated by Django 6.1.1 on 2026-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role name or Degree name', max_length=150)),
                ('organization', models.CharField(help_text='Company or University name', max_length=150)),
                ('type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education')], default='work', max_length=20)),
                ('start_date', models.CharField(help_text='e.g., Jan 2023', max_length=50)),
                ('end_date', models.CharField(default='Present', help_text='e.g., Dec 2024 or Present', max_length=50)),
                ('description', models.TextField(help_text='Key responsibilities, courses, or achievements')),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(help_text='Short blurb for project cards', max_length=300)),
                ('description', models.TextField(help_text='Detailed markdown or plain text description')),
                ('category', models.CharField(choices=[('Web', 'Web Development'), ('AI', 'AI & Machine Learning'), ('Mobile', 'Mobile Applications'), ('DevOps', 'Cloud & DevOps')], default='Web', max_length=50)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', help_text='Direct link to project screenshot or thumbnail')),
                ('github_url', models.URLField(blank=True, help_text='GitHub Repository Link')),
                ('live_demo_url', models.URLField(blank=True, help_text='Live Working Demo Link')),
                ('technologies', models.CharField(help_text='Comma-separated tech list, e.g. Python, Django, PostgreSQL, HTML5, CSS3', max_length=250)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('Database', 'Database & ORM'), ('Tools', 'Tools, Cloud & DevOps')], default='Backend', max_length=50)),
                ('proficiency', models.IntegerField(default=85, help_text='Proficiency percentage (1 to 100)')),
                ('icon', models.CharField(default='code', help_text='Lucide or FontAwesome icon slug (e.g. python, database, layout, terminal)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
