# Generated by Django 6.1.1 on 2026-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Frameworks & Web', 'Frameworks & Web')], default='Programming Languages', max_length=50),
        ),
    ]
